[versions]
kotlin = "2.2.21"
ktx-serialization = "1.9.0"
ktx-coroutines = "1.10.2"
ktx-atomicfu = "0.28.0"
ktx-datetime = "0.6.2"
exposed = "0.61.0"
koin = "4.1.0"
koinKtor = "4.1.0"
log4j = "2.25.0"
ktor = "3.2.1"
snowflake-id = "0.0.2"
postgresql = "42.7.7"
javaJwt = "4.5.0"
docker-kotlin = "0.6.0"
bcprov = "1.81"
validator = "9.0.1.Final"
expressly = "6.0.0"
plugin-shadowjar = "8.3.6"
detekt = "1.23.8"
hocon = "1.4.3"
lettuce = "7.2.0.RELEASE"

[libraries]
ktx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "ktx-atomicfu" }
ktx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "ktx-datetime" }
ktx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "ktx-serialization" }
ktx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktx-serialization" }
ktx-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "ktx-serialization" }
ktx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "ktx-coroutines" }
ktx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "ktx-coroutines" }
ktx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "ktx-coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koinKtor" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-test = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor-server-feature-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-server-feature-defaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-feature-autoHeadResponse = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
ktor-server-feature-calllogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-feature-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-feature-statuspages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-feature-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-feature-dataConversion = { module = "io.ktor:ktor-server-data-conversion", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-feature-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-client-feature-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
snowflakeId = { module = "de.mkammerer.snowflake-id:snowflake-id", version.ref = "snowflake-id" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
javaJwt = { module = "com.auth0:java-jwt", version.ref = "javaJwt" }
dockerKotlin = { module = "me.devnatan:yoki", version.ref = "docker-kotlin" }
bcprov = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bcprov" }
expressly = { module = "org.glassfish.expressly:expressly", version.ref = "expressly" }
validator = { module = "org.hibernate.validator:hibernate-validator", version.ref = "validator" }
validator-processor = { module = "org.hibernate.validator:hibernate-validator-annotation-processor", version.ref = "validator" }
hocon = { module = "com.typesafe:config", version.ref = "hocon" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }

[bundles]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-kotlin-datetime"]
ktor = ["ktor-server-core",
    "ktor-server-cio",
    "ktor-server-feature-calllogging",
    "ktor-server-feature-defaultHeaders",
    "ktor-server-feature-resources",
    "ktor-server-feature-statuspages",
    "ktor-server-feature-autoHeadResponse",
    "ktor-server-feature-cors",
    "ktor-server-websockets",
    "ktor-server-feature-contentNegotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-server-auth",
    "ktor-server-auth-jwt",
    "ktor-server-openapi",
    "ktor-server-swagger",
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadowjar = { id = "com.gradleup.shadow", version.ref = "plugin-shadowjar" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.3.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktor = { id = "io.ktor.plugin", version = "3.3.3" }