services:
  kuken:
    container_name: kuken-node-1
    build:
      context: .
      dockerfile: local.Dockerfile
    restart: on-failure
    command: [ "/bin/bash", "-c", "./gradlew runFatJar" ]
    ports:
      - "8080:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/kuken/logs:/usr/kuken/logs"
    environment:
      DB_HOST: kuken_database
      DB_PASS: kuken
      DOCKER_HOST: tcp://database:2375
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - kuken_network

  postgres:
    image: postgres:latest
    restart: on-failure
    hostname: kuken_database
    environment:
      POSTGRES_USER: kuken
      POSTGRES_PASSWORD: kuken
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kuken" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - kuken_network

  redis:
    image: redis:latest
    restart: on-failure
    hostname: kuken_redis
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: kuken
      REDIS_PASSWORD: kuken
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - kuken_network

volumes:
  postgres_data:
    driver: local

networks:
  kuken_network:
    driver: bridge
